### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Clownses** [ylabio/yii2-administer#33]
Greetings. If you try to install your module, an error occurs.
  - The requested package ylab / yii2-administer could not be found in any version, there may be a typo in the package name.
Tell me how to solve this problem?
Links for the compomer were taken from your repository

**Comment by senor-artemisio** [comment]
add repository section:

"repositories": [
        {
            "type": "composer",
            "url": "https://asset-packagist.org"
        },
        {
            "type": "git",
            "url": "https://github.com/ylabio/yii2-administer"
        }
    ]

**Comment by Clownses** [comment]
Tried, did not help

**Comment by senor-artemisio** [comment]
can you show your composer commands that you run and composer.json file

**Comment by Clownses** [comment]
composer update --ignore-platform-reqs
Loading composer repositor
Updating dependencies (including require-dev) 

  Problem 1
    - The requested package ylabio/yii2-administer could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

`{
    "name": "Application",
    "description": "Source",
    "keywords": ["yii2"],
    "homepage": "http://yii2.loc",
    "type": "project",
    "license": "MIT",
    "support": {
        "source": "http://yii2.loc"
    },
    "minimum-stability": "stable",
    "require": {
        "yiisoft/yii2": "~2.0.5",
        "yiisoft/yii2-bootstrap": "~2.0.0",
        "yiisoft/yii2-swiftmailer": "~2.0.0",
        "yiisoft/yii2-authclient": "~2.0.6",
        "cebe/yii2-gravatar": "~1.1",
        "demi/comments": "~1.0",
        "bower-asset/codemirror": "~5.9.0",
        "bower-asset/codemirror-buttons": "~1.0.0",
        "dignityinside/translithelper": "^0.01.0",
        "kartik-v/yii2-widget-select2": "^2.1",
        "himiklab/yii2-easy-thumbnail-image-helper" : "*",
        "kop/yii2-scroll-pager": "*",
        "vision/yii2-private-messages": "^2",
        "karnbrockgmbh/yii2-modal-ajax": "@dev",
        "kartik-v/yii2-widget-datetimepicker": "*",
        "kartik-v/yii2-widget-datepicker": "@dev",
        "kartik-v/yii2-field-range": "*",
        "kartik-v/yii2-widget-timepicker": "*",
        "kartik-v/yii2-widget-fileinput": "@dev",
        "yii2mod/yii2-google-maps-markers": "*",
        "kartik-v/yii2-widget-activeform": "@dev",
        "2amigos/yii2-ckeditor-widget" : "~1.0",
        "dmstr/yii2-adminlte-asset": "2.*",
        "ylabio/yii2-administer": "*"
    },
    "require-dev": {
        "yiisoft/yii2-debug": "~2.0.0",
        "yiisoft/yii2-gii": "~2.0.0"
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://asset-packagist.org"
        },
        {
        "type": "git",
        "url": "https://github.com/ylabio/yii2-administer"
        }
    ],
    "config": {
        "process-timeout": 1800
    },
    "scripts": {
        "post-create-project-cmd": [
            "yii\\composer\\Installer::postCreateProject"
        ]
    },
    "extra": {
        "yii\\composer\\Installer::postCreateProject": {
            "setPermission": [
                {
                    "runtime": "0777",
                    "web/assets": "0777",
                    "yii": "0755"
                }
            ],
            "generateCookieValidationKey": [
                "config/web.php"
            ]
        },
        "asset-installer-paths": {
            "npm-asset-library": "vendor/npm",
            "bower-asset-library": "vendor/bower"
        }
    }
}
`

**Comment by senor-artemisio** [comment]
You used wrong package name "ylabio/yii2-administer", you should use correct package name is "ylab/yii2-administer"

**Comment by Clownses** [comment]
I'm sorry, my typo. I tried both. And the error arises in both cases

 Problem 1
    - The requested package ylab/yii2-administer could not be found in any version, there may be a typo in the package name.

 Problem 1
    - The requested package ylabio/yii2-administer could not be found in any version, there may be a typo in the package name.

**Comment by Clownses** [comment]
Could you send me an archive with the files that were installed through the composer? I will establish all the dependencies myself.

**Comment by Clownses** [comment]
After the dances with a tambourine, we managed to upload the files. However, when connecting, an error occurs - Class ylab\administer\Module does not exist
The path to the module files - vendor\ylab\administer\src

**Comment by senor-artemisio** [comment]
i can review your code if you can publish it on github

**Comment by Clownses** [comment]
What kind of code do you need?
I just copied the files from the repository, put them in the right folder, installed all the dependencies, and made the connection in the web.php file

**Comment by senor-artemisio** [comment]
i found typo in readme. fixed.

try this composer.json it's works

```json
{
    "name": "some/project",
    "type": "project",
    "require": {
        "ylab/administer": "*"
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://asset-packagist.org"
        },
        {
            "type": "git",
            "url": "https://github.com/ylabio/yii2-administer"
        }
    ]
}
```

**Comment by Clownses** [comment]
Thank you so much. This solved my problem
